### ISSUE TITLE
Available and Planned tool lists don't show as both (in the middle)

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-crosscheck-tools#17] opened 2018-04-02 15:12 UTC
See e.g. tools like JFMI or "Virtual Engine" - they both import and export but are not listed in the middle.

**Comment by xogeny** [comment] 2018-04-03 14:29
Nothing lists in the middle.  This is by design.  The problem is that it isn't obvious (to me) how this should work.  What if a tool plans support for import but has cross-check data for export?  What about if it has available (non-cross-checked) support for import but available support for export?

If it is pure cross-check data, then it works because we can just report the results of the cross-checking.  But planned and available are a different "type" of data and so it is not obviously how to "mix" them into the cross-check data.

You may not like the way it is done now, but if you want it done differently, we need a *complete specification* for how it should work.  As I said, I looked at this and I wasn't able to come up with something that I felt worked well.  But if the FMI group decides on something, I will implement it.  I just don't want the responsibility of designing/specifying because it is a tricky issue and it will require many iterations if it works at all.

**Comment by andreas-junghanns** [comment] 2018-04-03 14:45
I totally agree for mixed types - those cannot be resolved.
But what we have now for some tools is that they claim to have export and claim to have import and therefore the tool is listed for both types (left and right).
I would think - ok, I might miss some details - that if something is on both sides, then it should move to the middle. And always only looking at the same type.
If this causes confusion, ok, then I am also not sure how this should be done because mixing type would leave us at least with the question where to place the resulting new "mixed-type" - my head hurts just writing this down.

**Comment by xogeny** [comment] 2018-04-03 22:28
How about this very limited case.  If something supports import and export *in exactly the same way*, then it moves to the middle.  In other words, if it is "planned" for both import and export.  But it doesn't have exactly the same level of support for both import and export, then it gets split up to the left and right?

Would that address your concern?  Note that this could turn into a slippery slope with people then saying "but my tool plans to support import but already supports export, but it isn't in the middle".  But that is the kind of thing we can deal with if it happens...so long as we agree now that those are the limits of the functionality, we can always push back against such requests.

**Comment by andreas-junghanns** [comment] 2018-04-04 06:06
Yes, this is how I would read those three classes of compliance (XC, claim, planned) and the three kinds (import, import+export, export). And I think keeping it that simple will cause the least confusion (I know that I have said that before).

**Comment by andreas-junghanns** [comment] 2018-04-04 08:06
STOP!!!! We are now discussing this in Dresden and people here think that the middle column is actually not helping but forces people to search tools in more than one column. So here we are leaning towards removing the middle (import and export) column entirely. Would that be simple to implement?

**Comment by andreas-junghanns** [comment] 2018-04-04 08:11
Another reason to remove the middle column will also help when we add more filter criteria in the future (like feature support) - with the middle column the combinatorics will kill us eventually.

**Comment by xogeny** [comment] 2018-04-04 14:30
@andreas-junghanns Please confirm that you want to move to a two column format (I can do it quickly).

As for the white space to the left and right, that is a separate issue and is related entirely to the CSS setup by MangoWeb and nothing to do with my work here.  That being said, I've "fixed" that issue in the past by removing *some* whitespace already.  If you want to make the site consume any available width (*i.e.,* fixed width margins on the left and the right), open a ticket on the fmi-standard.org repo and assign it to me and I can fix that as well.

**Comment by andreas-junghanns** [comment] 2018-04-04 14:34
Yes, please move to 2-columns - and mark the commit so in case we reverse this decision in the future, we can undo it (sorry, typical committee work).

**Closed** 2018-04-05 01:16 UTC

**Comment by xogeny** [comment] 2018-04-05 01:19
No more middle column.  You can go to https://preview.fmi-standard.org/tools/ to see the result.

For anybody interested (some future intrepid volunteer who wants to help improve the FMI web site), you can see exactly what change were required in d5aa71a.  Note that what I did was create two versions of the support matrix view.  One supports two columns and one supports three columns.  To address @andreas-junghanns's concern about reverting, I kept the previous component (now named `ThreeColumnView`) around but we are now using `TwoColumnView` as discussed in this thread.

**Comment by andreas-junghanns** [comment] 2018-04-05 07:14
Wonderful and quick - thank you (from Dresden!)
